In [1]:
import json
import pathlib

import pandas as pd

base_model_path = pathlib.Path(
    "../../runs/helpdesk_1/100%/20250307.2050.no_constraint/"
)
constraints_task_fine_tuned_model_path = pathlib.Path(
    "../../runs/helpdesk_1/100%/20250308.1124.constraints/"
)
constraints_fine_tuned_model_path = pathlib.Path(
    "../../runs/helpdesk_1/100%/20250308.1247.constraints/"
)

alt_dataset_constraints_task_fine_tuned_model_path = pathlib.Path(
    "../../runs/helpdesk_2/100%/20250311.1316.constraints"
)
alt_dataset_constraints_fine_tuned_model_path = pathlib.Path(
    "../../runs/helpdesk_2/100%/20250311.1320.constraints"
)
alt_dataset_task_fine_tuned_model_path = pathlib.Path(
    "../../runs/helpdesk_2/100%/20250311.1316.no_constraint"
)

### Tests over `helpdesk_1`

In [2]:
pd.DataFrame.from_records(
    [
        {"model": "base"}
        | json.loads(
            (
                base_model_path.rglob("*.best_val_acc/*/results.json")
                .__next__()
                .read_text()
            )
        ),
        {"model": "fine_tuned"}
        | json.loads(
            (
                constraints_task_fine_tuned_model_path.rglob(
                    "*.best_val_acc/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "constraints_only_fine_tuned"}
        | json.loads(
            (
                constraints_fine_tuned_model_path.rglob("*.best_val_acc/*/results.json")
                .__next__()
                .read_text()
            )
        ),
        {"model": "alt_dataset_fine_tuned"}
        | json.loads(
            (
                alt_dataset_constraints_task_fine_tuned_model_path.rglob(
                    "*.best_val_acc/helpdesk_1/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "constraints_only_alt_dataset_fine_tuned"}
        | json.loads(
            (
                alt_dataset_constraints_fine_tuned_model_path.rglob(
                    "*.best_val_acc/helpdesk_1/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "task_only_alt_dataset_fine_tuned"}
        | json.loads(
            (
                alt_dataset_task_fine_tuned_model_path.rglob(
                    "*.best_val_acc/helpdesk_1/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
    ],
    index="model",
)

,loss,acc,dld,norm_dld,weighted_norm_dld
model,,,,,
base,0.114083,0.875843,2.173228,0.103882,0.124157
fine_tuned,0.734311,0.641026,6.275590,0.330345,0.358525
constraints_only_fine_tuned,1.052686,0.001350,17.480314,0.998082,0.998650
alt_dataset_fine_tuned,0.623826,0.371570,11.000000,0.469143,0.628430
constraints_only_alt_dataset_fine_tuned,0.525834,0.669816,5.771654,0.280570,0.329735
task_only_alt_dataset_fine_tuned,0.375442,0.699505,5.259842,0.233390,0.300495

### Tests over `helpdesk_2`

In [3]:
pd.DataFrame.from_records(
    [
        {"model": "base"}
        | json.loads(
            (
                base_model_path.rglob("*.best_val_acc/helpdesk_2/*/results.json")
                .__next__()
                .read_text()
            )
        ),
        {"model": "fine_tuned"}
        | json.loads(
            (
                constraints_task_fine_tuned_model_path.rglob(
                    "*.best_val_acc/helpdesk_2/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "constraints_only_fine_tuned"}
        | json.loads(
            (
                constraints_fine_tuned_model_path.rglob(
                    "*.best_val_acc/helpdesk_2/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "alt_dataset_fine_tuned"}
        | json.loads(
            (
                alt_dataset_constraints_task_fine_tuned_model_path.rglob(
                    "*.best_val_acc/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "constraints_only_alt_dataset_fine_tuned"}
        | json.loads(
            (
                alt_dataset_constraints_fine_tuned_model_path.rglob(
                    "*.best_val_acc/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
        {"model": "task_only_alt_dataset_fine_tuned"}
        | json.loads(
            (
                alt_dataset_task_fine_tuned_model_path.rglob(
                    "*.best_val_acc/*/results.json"
                )
                .__next__()
                .read_text()
            )
        ),
    ],
    index="model",
)

,loss,acc,dld,norm_dld,weighted_norm_dld
model,,,,,
base,0.355138,0.525862,9.166667,0.352564,0.474138
fine_tuned,0.617146,0.431034,11.000000,0.423077,0.568965
constraints_only_fine_tuned,0.709800,0.000000,19.333334,1.000000,1.000000
alt_dataset_fine_tuned,0.599543,0.431034,11.000000,0.423077,0.568965
constraints_only_alt_dataset_fine_tuned,0.690873,0.224138,15.000000,0.833333,0.775862
task_only_alt_dataset_fine_tuned,0.050604,0.896552,2.000000,0.076923,0.103448