# Evaluation for BPI Challenge 2017 models

Inside the folder `<project_root>/runs/bpic2017` we have a list of folders named as `<percentage>%`, where `<percentage>` is the percentage of the dataset used for training the model.
In each of these folders we have a folder named as the best model found during the training phase based on the accuracy value.
Inside each of these folders we have the following files:
- `constraints_satisfaction_rate.csv`: a CSV file containing the constraints satisfaction rate for each of the test traces.
- `constraints_satisfactions.csv`: a CSV file containing the constraints satisfaction for each of the test traces.
- `predicted_traces.txt`: a TXT file containing the traces generated by the model for each of the test traces.
- `predictions.csv`: a CSV file containing the predictions step by step for each of the test traces.
- `results.json`: a JSON file containing the results of the evaluation of the model on the test set.

In [1]:
DATASET_NAME = "bpic2017"

In [2]:
from collections import namedtuple
import pathlib

project_root = pathlib.Path("../../..").parent.resolve()

Info = namedtuple("Info", ["model_args", "model_path", "results_path"])

models_path: dict[int, list[Info]] = {}

for dataset_percentage in range(20, 101, 20):
    checkpoints = [
        path
        for path in (project_root / "runs" / DATASET_NAME).rglob(
            f"{dataset_percentage}%/**/*.best_val_acc.pth"
        )
    ]
    results = [
        pathlib.Path(str(checkpoint).removesuffix(".pth"))
        / "step_by_step"
        / "results.json"
        for checkpoint in checkpoints
    ]
    args = [checkpoint.parent / "args.json" for checkpoint in checkpoints]
    models_path[dataset_percentage] = [
        Info(model_args=args, model_path=checkpoint, results_path=result)
        for args, checkpoint, result in zip(args, checkpoints, results)
    ]

## Comparison

In [3]:
import json
import pandas as pd

dataframes = {}

for percentage in models_path:
    dataframes[percentage] = pd.DataFrame(
        columns=[
            "lr",
            "dropout",
            "loss",
            "acc",
            "dld",
            "norm_dld",
            "constraints",
            "constraints_multiplier",
        ]
    )
    for info in models_path[percentage]:
        with open(info.model_args) as f:
            args = json.load(f)
        try:
            with open(info.results_path) as f:
                results = json.load(f)
                dataframes[percentage].loc[info.model_path.parent.name] = [
                    args["learning_rate"],
                    args["model"]["dropout"],
                    results["loss"],
                    results["acc"],
                    results["dld"],
                    results["norm_dld"],
                    args.get("constraints", None),
                    args.get("constraints_multiplier", None),
                ]
        except FileNotFoundError:
            print(f"Missing results for {info.model_path}")

/tmp/ipykernel_512957/703172264.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataframes[percentage].loc[info.model_path.parent.name] = [

In [4]:
for percentage in range(20, 101, 20):
    print("=" * 10 + f" {percentage}% " + "=" * 10)
    display(dataframes[percentage].sort_values("dld", ascending=True))
    print()

========== 20% ==========

,lr,dropout,loss,acc,dld,norm_dld,constraints,constraints_multiplier
20250307.0812.no_constraint,0.0001,0.2,0.931325,0.88443,1.69437,0.125181,[],None

========== 40% ==========

,lr,dropout,loss,acc,dld,norm_dld,constraints,constraints_multiplier
20250307.0853.no_constraint,0.0001,0.2,0.920632,0.885082,1.666888,0.126055,[],None

========== 60% ==========

,lr,dropout,loss,acc,dld,norm_dld,constraints,constraints_multiplier
20250307.1014.no_constraint,0.0001,0.2,0.902772,0.883767,1.683348,0.127469,[],None

========== 80% ==========

,lr,dropout,loss,acc,dld,norm_dld,constraints,constraints_multiplier
20250307.1212.no_constraint,0.0001,0.2,0.975154,0.882248,1.682555,0.130207,[],None

========== 100% ==========

,lr,dropout,loss,acc,dld,norm_dld,constraints,constraints_multiplier
20250307.1456.no_constraint,0.0001,0.2,0.957479,0.883796,1.619998,0.128651,[],NaN
20250312.0056.constraints,0.0001,0.2,1.307675,0.877115,1.715254,0.132079,"[Exactly1[A_Accepted], Alternate Succession[A_...",0.1