In [1]:
import json
import pathlib

import pandas as pd

pd.set_option("max_colwidth", 400)

prefix = "dataset_declare_D=3_C=3"
separator = "_"
runs = [run for run in pathlib.Path("../../runs/").glob(f"{prefix}{separator}*")]
assert len(runs) == 5
for run in runs:
    print(run.name)

dataset_declare_D=3_C=3_f-01-nw-1000-ml-20-0
dataset_declare_D=3_C=3_f-02-nw-1000-ml-20-0
dataset_declare_D=3_C=3_f-03-nw-1000-ml-20-0
dataset_declare_D=3_C=3_f-04-nw-1000-ml-20-0
dataset_declare_D=3_C=3_f-05-nw-1000-ml-20-0

In [2]:
def evaluate(run):
    print(
        f"Evaluating models trained on",
        prefix,
        run.stem.removeprefix(prefix + separator),
    )
    models = [args.parent for args in run.rglob("args.json")]

    results_records = []
    for model in models:
        args = json.loads(model.joinpath("args.json").read_text())
        # print(args["constraints"])
        # print(args.get("constraints_multiplier", None))
        results = model.glob("**/results.json").__next__()
        # print(model.name)
        # print(results.read_text())
        results = json.loads(results.read_text())
        results_records.append(
            {
                "model": model.name,
                "constraints": args["constraints"],
                "constraints_multiplier": args.get("constraints_multiplier", None),
                "acc": results["acc"],
                "dld": results["dld"],
                "norm_dld": results["norm_dld"],
                "weighted_norm_dld": results["weighted_norm_dld"],
            }
        )

    df = pd.DataFrame(results_records, index=[r["model"] for r in results_records])
    df = df.drop(columns=["model"])
    df = df.sort_values(by="dld", ascending=True)
    display(df)

In [3]:
for run in runs:
    evaluate(run)
    print()

Evaluating models trained on dataset_declare_D=3_C=3 f-01-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250318.0846.no_constraint,[],NaN,0.429101,15.047619,0.500000,0.501587
20250318.1101.constraints,"[Alternate Succession[c, a], Co-Existence[c, b], Responded Existence[b, b], Alternate Precedence[a, c]]",0.1,0.391534,17.111111,0.571009,0.570370
20250318.1007.constraints,"[Responded Existence[a, c], Alternate Precedence[a, b], Alternate Succession[c, a], Chain Succession[c, a], Not CoExistence[a, b]]",0.1,0.377778,17.587301,0.586462,0.586243
20250318.0853.constraints,"[Not Chain Succession[c, b], Succession[a, c]]",0.1,0.399471,17.761906,0.591918,0.592063
20250318.0902.constraints,"[Chain Succession[a, a], Chain Response[c, c]]",0.1,0.383598,18.492064,0.617025,0.616402

Evaluating models trained on dataset_declare_D=3_C=3 f-02-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250318.0848.no_constraint,[],NaN,0.361376,17.587301,0.587607,0.586243
20250318.1152.constraints,"[Responded Existence[a, c], Alternate Precedence[a, b], Alternate Succession[c, a], Chain Succession[c, a], Not CoExistence[a, b]]",0.1,0.358730,18.603174,0.619238,0.620106
20250318.1247.constraints,"[Alternate Succession[c, a], Co-Existence[c, b], Responded Existence[b, b], Alternate Precedence[a, c]]",0.1,0.355556,19.111111,0.636600,0.637037
20250318.0906.constraints,"[Not Chain Succession[c, b], Succession[a, c]]",0.1,0.346561,19.412699,0.647512,0.647090
20250318.0915.constraints,"[Chain Succession[a, a], Chain Response[c, c]]",0.1,0.349206,19.523809,0.651213,0.650794

Evaluating models trained on dataset_declare_D=3_C=3 f-03-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250318.0849.no_constraint,[],NaN,0.407937,16.253969,0.542277,0.541799
20250318.1340.constraints,"[Responded Existence[a, c], Alternate Precedence[a, b], Alternate Succession[c, a], Chain Succession[c, a], Not CoExistence[a, b]]",0.1,0.395767,17.380953,0.578640,0.579365
20250318.0919.constraints,"[Not Chain Succession[c, b], Succession[a, c]]",0.1,0.402116,17.492064,0.583371,0.583069
20250318.1433.constraints,"[Alternate Succession[c, a], Co-Existence[c, b], Responded Existence[b, b], Alternate Precedence[a, c]]",0.1,0.406878,17.555555,0.584554,0.585185
20250318.0929.constraints,"[Chain Succession[a, a], Chain Response[c, c]]",0.1,0.391534,17.714285,0.592033,0.590476

Evaluating models trained on dataset_declare_D=3_C=3 f-04-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250318.0851.no_constraint,[],NaN,0.391005,17.380953,0.580472,0.579365
20250318.1523.constraints,"[Responded Existence[a, c], Alternate Precedence[a, b], Alternate Succession[c, a], Chain Succession[c, a], Not CoExistence[a, b]]",0.1,0.347619,18.507936,0.616720,0.616931
20250318.1617.constraints,"[Alternate Succession[c, a], Co-Existence[c, b], Responded Existence[b, b], Alternate Precedence[a, c]]",0.1,0.329101,18.777779,0.625954,0.625926
20250318.0942.constraints,"[Chain Succession[a, a], Chain Response[c, c]]",0.1,0.359788,19.190475,0.641255,0.639683
20250318.0933.constraints,"[Not Chain Succession[c, b], Succession[a, c]]",0.1,0.350265,19.460318,0.650030,0.648677

Evaluating models trained on dataset_declare_D=3_C=3 f-05-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250318.0852.no_constraint,[],NaN,0.383069,16.380953,0.546589,0.546032
20250318.1708.constraints,"[Responded Existence[a, c], Alternate Precedence[a, b], Alternate Succession[c, a], Chain Succession[c, a], Not CoExistence[a, b]]",0.1,0.400529,16.968254,0.566087,0.565608
20250318.1801.constraints,"[Alternate Succession[c, a], Co-Existence[c, b], Responded Existence[b, b], Alternate Precedence[a, c]]",0.1,0.381481,17.412699,0.580090,0.580423
20250318.0955.constraints,"[Chain Succession[a, a], Chain Response[c, c]]",0.1,0.366667,18.730158,0.624695,0.624339
20250318.0946.constraints,"[Not Chain Succession[c, b], Succession[a, c]]",0.1,0.351323,19.031746,0.634463,0.634392