In [1]:
import json
import pathlib

import pandas as pd

pd.set_option("max_colwidth", 400)

prefix = "dataset_declare_D=1_C=5"
separator = "_"
runs = [run for run in pathlib.Path("../../runs/").glob(f"{prefix}{separator}*")]
assert len(runs) == 5
for run in runs:
    print(run.name)

dataset_declare_D=1_C=5_f-01-nw-1000-ml-20-0
dataset_declare_D=1_C=5_f-02-nw-1000-ml-20-0
dataset_declare_D=1_C=5_f-03-nw-1000-ml-20-0
dataset_declare_D=1_C=5_f-04-nw-1000-ml-20-0
dataset_declare_D=1_C=5_f-05-nw-1000-ml-20-0

In [2]:
def evaluate(run):
    print(
        f"Evaluating models trained on",
        prefix,
        run.stem.removeprefix(prefix + separator),
    )
    models = [args.parent for args in run.rglob("args.json")]

    results_records = []
    for model in models:
        args = json.loads(model.joinpath("args.json").read_text())
        # print(args["constraints"])
        # print(args.get("constraints_multiplier", None))
        results = model.glob("**/results.json").__next__()
        # print(model.name)
        # print(results.read_text())
        results = json.loads(results.read_text())
        results_records.append(
            {
                "model": model.name,
                "constraints": args["constraints"],
                "constraints_multiplier": args.get("constraints_multiplier", None),
                "acc": results["acc"],
                "dld": results["dld"],
                "norm_dld": results["norm_dld"],
                "weighted_norm_dld": results["weighted_norm_dld"],
            }
        )

    df = pd.DataFrame(results_records, index=[r["model"] for r in results_records])
    df = df.drop(columns=["model"])
    df = df.sort_values(by="dld", ascending=True)
    display(df)

In [3]:
for run in runs:
    evaluate(run)
    print()

Evaluating models trained on dataset_declare_D=1_C=5 f-01-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.1312.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.01,0.387831,16.968254,0.567346,0.565608
20250316.1530.constraints,[Existence2[c]],0.10,0.390476,17.492064,0.585203,0.583069
20250316.1328.constraints,"[Response[c, a]]",0.01,0.391534,17.507936,0.585012,0.583598
20250316.1512.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.10,0.390476,17.539682,0.586691,0.584656
20250316.1326.constraints,[Existence2[c]],0.01,0.387302,17.571428,0.587569,0.585714
20250316.1309.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.01,0.386243,17.650793,0.590278,0.588360
20250316.1716.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",1.00,0.374074,17.666666,0.590774,0.588889
20250316.1303.no_constraint,[],NaN,0.386772,17.746031,0.593597,0.591534
20250316.1532.constraints,"[Response[c, a]]",0.10,0.385714,18.222221,0.606990,0.607407
20250316.1515.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.10,0.370899,18.253969,0.610157,0.608466
20250316.1732.constraints,[Existence2[c]],1.00,0.326984,19.380953,0.647894,0.646032
20250316.1735.constraints,"[Response[c, a]]",1.00,0.349735,19.507936,0.649458,0.650265
20250316.1719.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",1.00,0.323280,20.301588,0.676663,0.676720

Evaluating models trained on dataset_declare_D=1_C=5 f-02-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.1353.constraints,"[Response[c, a]]",0.01,0.396296,16.174603,0.537851,0.539153
20250316.1337.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.01,0.388889,16.269842,0.540827,0.542328
20250316.1304.no_constraint,[],NaN,0.390476,16.396826,0.545139,0.546561
20250316.1350.constraints,[Existence2[c]],0.01,0.395238,16.412699,0.545749,0.547090
20250316.1555.constraints,[Existence2[c]],0.10,0.393122,16.428572,0.546131,0.547619
20250316.1334.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.01,0.392593,16.460318,0.547352,0.548677
20250316.1538.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.10,0.371958,16.809525,0.559524,0.560317
20250316.1740.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",1.00,0.382540,17.047619,0.566964,0.568254
20250316.1558.constraints,"[Response[c, a]]",0.10,0.375661,17.984127,0.601152,0.599471
20250316.1758.constraints,[Existence2[c]],1.00,0.352910,18.333334,0.610233,0.611111
20250316.1801.constraints,"[Response[c, a]]",1.00,0.371958,18.587301,0.621032,0.619577
20250316.1541.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.10,0.338624,18.920635,0.629960,0.630688
20250316.1743.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",1.00,0.324339,20.269842,0.676129,0.675661

Evaluating models trained on dataset_declare_D=1_C=5 f-03-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.1604.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.10,0.414815,14.523809,0.483517,0.484127
20250316.1358.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.01,0.410582,14.571428,0.485806,0.485714
20250316.1305.no_constraint,[],NaN,0.412698,14.650794,0.488057,0.488360
20250316.1621.constraints,[Existence2[c]],0.10,0.419048,14.777778,0.492483,0.492593
20250316.1415.constraints,[Existence2[c]],0.01,0.414815,14.793651,0.492979,0.493122
20250316.1417.constraints,"[Response[c, a]]",0.01,0.422751,14.841269,0.494009,0.494709
20250316.1401.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.01,0.404762,14.984127,0.498817,0.499471
20250316.1806.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",1.00,0.387831,15.634921,0.522131,0.521164
20250316.1824.constraints,[Existence2[c]],1.00,0.383598,16.015873,0.534264,0.533862
20250316.1623.constraints,"[Response[c, a]]",0.10,0.411111,16.984127,0.566468,0.566138
20250316.1607.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.10,0.371958,17.301588,0.576961,0.576720
20250316.1810.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",1.00,0.314286,18.412699,0.614774,0.613757
20250316.1826.constraints,"[Response[c, a]]",1.00,0.375661,18.714285,0.623741,0.623810

Evaluating models trained on dataset_declare_D=1_C=5 f-04-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.1426.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.01,0.403175,15.730159,0.523619,0.524339
20250316.1832.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",1.00,0.361376,15.904762,0.529876,0.530159
20250316.1644.constraints,[Existence2[c]],0.10,0.392593,15.984127,0.532700,0.532804
20250316.1439.constraints,[Existence2[c]],0.01,0.393122,16.015873,0.533463,0.533862
20250316.1849.constraints,[Existence2[c]],1.00,0.393651,16.015873,0.533921,0.533862
20250316.1307.no_constraint,[],NaN,0.392063,16.142857,0.538233,0.538095
20250316.1629.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.10,0.391534,16.142857,0.537660,0.538095
20250316.1423.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.01,0.393651,16.206348,0.539644,0.540212
20250316.1441.constraints,"[Response[c, a]]",0.01,0.394180,16.857143,0.561470,0.561905
20250316.1631.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.10,0.392063,17.380953,0.578869,0.579365
20250316.1647.constraints,"[Response[c, a]]",0.10,0.380952,18.206348,0.606265,0.606878
20250316.1835.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",1.00,0.348148,19.380953,0.647321,0.646032
20250316.1851.constraints,"[Response[c, a]]",1.00,0.290476,21.095238,0.702152,0.703175

Evaluating models trained on dataset_declare_D=1_C=5 f-05-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.1857.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",1.00,0.360847,17.412699,0.579632,0.580423
20250316.1914.constraints,[Existence2[c]],1.00,0.380952,17.603174,0.585814,0.586773
20250316.1450.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.01,0.382011,17.634920,0.588294,0.587831
20250316.1308.no_constraint,[],NaN,0.376720,17.857143,0.594895,0.595238
20250316.1504.constraints,[Existence2[c]],0.01,0.376720,17.857143,0.594780,0.595238
20250316.1447.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.01,0.376720,17.873016,0.595391,0.595767
20250316.1708.constraints,[Existence2[c]],0.10,0.375132,17.888889,0.595658,0.596296
20250316.1506.constraints,"[Response[c, a]]",0.01,0.375132,17.904762,0.596726,0.596825
20250316.1655.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",0.10,0.363492,18.380953,0.612637,0.612698
20250316.1711.constraints,"[Response[c, a]]",0.10,0.373545,18.507936,0.617063,0.616931
20250316.1917.constraints,"[Response[c, a]]",1.00,0.364021,19.079365,0.636065,0.635979
20250316.1652.constraints,"[Existence3[a], Existence3[b], Existence3[c]]",0.10,0.327513,19.412699,0.646596,0.647090
20250316.1900.constraints,"[Existence2[a], Succession[a, a], Response[c, c], Chain Succession[a, a]]",1.00,0.330159,20.015873,0.668651,0.667196