In [1]:
import json
import pathlib

import pandas as pd

pd.set_option("max_colwidth", 400)

prefix = "dataset_declare_D=2_C=4"
separator = "_"
runs = [run for run in pathlib.Path("../../runs/").glob(f"{prefix}{separator}*")]
assert len(runs) == 5
for run in runs:
    print(run.name)

dataset_declare_D=2_C=4_f-01-nw-1000-ml-20-0
dataset_declare_D=2_C=4_f-02-nw-1000-ml-20-0
dataset_declare_D=2_C=4_f-03-nw-1000-ml-20-0
dataset_declare_D=2_C=4_f-04-nw-1000-ml-20-0
dataset_declare_D=2_C=4_f-05-nw-1000-ml-20-0

In [2]:
def evaluate(run):
    print(
        f"Evaluating models trained on",
        prefix,
        run.stem.removeprefix(prefix + separator),
    )
    models = [args.parent for args in run.rglob("args.json")]

    results_records = []
    for model in models:
        args = json.loads(model.joinpath("args.json").read_text())
        # print(args["constraints"])
        # print(args.get("constraints_multiplier", None))
        results = model.glob("**/results.json").__next__()
        # print(model.name)
        # print(results.read_text())
        results = json.loads(results.read_text())
        results_records.append(
            {
                "model": model.name,
                "constraints": args["constraints"],
                "constraints_multiplier": args.get("constraints_multiplier", None),
                "acc": results["acc"],
                "dld": results["dld"],
                "norm_dld": results["norm_dld"],
                "weighted_norm_dld": results["weighted_norm_dld"],
            }
        )

    df = pd.DataFrame(results_records, index=[r["model"] for r in results_records])
    df = df.drop(columns=["model"])
    df = df.sort_values(by="dld", ascending=True)
    display(df)

In [3]:
for run in runs:
    evaluate(run)
    print()

Evaluating models trained on dataset_declare_D=2_C=4 f-01-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.2050.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.01,0.394709,15.936508,0.528923,0.531217
20250317.0928.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.10,0.366138,16.666666,0.554945,0.555556
20250316.1923.no_constraint,[],NaN,0.368254,16.984127,0.565896,0.566138
20250316.1947.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.01,0.401058,17.047619,0.569483,0.568254
20250316.1930.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.01,0.391534,17.174603,0.573336,0.572487
20250317.2007.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",1.00,0.346561,17.777779,0.595505,0.592593
20250316.2039.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.01,0.371429,17.873016,0.593445,0.595767
20250317.0912.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.10,0.367725,18.111111,0.604319,0.603704
20250317.1030.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.10,0.365608,19.000000,0.635417,0.633333
20250317.1020.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.10,0.344974,19.634920,0.655487,0.654497
20250317.2113.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",1.00,0.272487,21.666666,0.723558,0.722222
20250317.2022.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",1.00,0.047619,28.571428,0.952381,0.952381
20250317.2122.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",1.00,0.007407,29.777779,0.992483,0.992593

Evaluating models trained on dataset_declare_D=2_C=4 f-02-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250316.1924.no_constraint,[],NaN,0.420106,15.333333,0.511676,0.511111
20250317.0007.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.01,0.410053,15.492064,0.515949,0.516402
20250316.2230.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.01,0.410053,15.555555,0.520223,0.518519
20250316.2215.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.01,0.416931,16.730158,0.559333,0.557672
20250317.1143.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.10,0.400529,16.825397,0.560363,0.560847
20250317.2156.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",1.00,0.389418,17.206348,0.574672,0.573545
20250316.2349.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.01,0.420106,17.238094,0.572802,0.574603
20250317.1128.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.10,0.400000,17.269842,0.576771,0.575661
20250317.1245.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.10,0.413227,17.603174,0.588561,0.586773
20250317.1235.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.10,0.383598,18.111111,0.605121,0.603704
20250317.2309.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",1.00,0.119577,26.333334,0.877633,0.877778
20250317.2211.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",1.00,0.000529,29.984127,0.999504,0.999471
20250317.2319.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",1.00,0.000000,30.000000,1.000000,1.000000

Evaluating models trained on dataset_declare_D=2_C=4 f-03-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250317.0240.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.01,0.363492,16.253969,0.542506,0.541799
20250316.1926.no_constraint,[],NaN,0.359788,16.428572,0.549794,0.547619
20250317.1336.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.10,0.362434,17.095238,0.572115,0.569841
20250317.0126.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.01,0.376720,17.158730,0.575015,0.571958
20250317.1352.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.10,0.342328,17.523809,0.585050,0.584127
20250317.0143.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.01,0.354497,18.333334,0.612981,0.611111
20250317.0230.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.01,0.358201,18.634920,0.620688,0.621164
20250317.1443.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.10,0.357672,19.253969,0.640491,0.641799
20250317.2350.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",1.00,0.339153,19.396826,0.649763,0.646561
20250317.1453.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.10,0.351852,19.444445,0.650565,0.648148
20250318.0100.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",1.00,0.347090,19.476191,0.648123,0.649206
20250318.0006.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",1.00,0.034921,28.952381,0.964858,0.965079
20250318.0109.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",1.00,0.000000,30.000000,1.000000,1.000000

Evaluating models trained on dataset_declare_D=2_C=4 f-04-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250317.0515.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.01,0.376190,15.523809,0.520032,0.517460
20250316.1927.no_constraint,[],NaN,0.396825,15.746032,0.525832,0.524868
20250317.0403.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.01,0.385714,16.158730,0.539873,0.538624
20250317.1603.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.10,0.375132,16.444445,0.548573,0.548148
20250317.1548.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.10,0.389418,17.126984,0.572535,0.570899
20250317.0418.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.01,0.405820,17.206348,0.574557,0.573545
20250317.0505.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.01,0.372487,17.412699,0.582036,0.580423
20250318.0141.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",1.00,0.356085,17.761906,0.593635,0.592063
20250317.1702.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.10,0.388889,18.333334,0.610806,0.611111
20250317.1652.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.10,0.340741,19.666666,0.656250,0.655556
20250318.0246.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",1.00,0.324339,20.063492,0.669452,0.668783
20250318.0156.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",1.00,0.047619,28.571428,0.952381,0.952381
20250318.0255.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",1.00,0.012169,29.634920,0.987904,0.987831

Evaluating models trained on dataset_declare_D=2_C=4 f-05-nw-1000-ml-20-0

,constraints,constraints_multiplier,acc,dld,norm_dld,weighted_norm_dld
20250317.0638.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.01,0.399471,15.968254,0.532089,0.532275
20250317.0653.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.01,0.394180,16.317461,0.542888,0.543915
20250317.1811.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",0.10,0.396825,16.603174,0.553190,0.553439
20250317.1756.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",0.10,0.379894,16.825397,0.561279,0.560847
20250317.0750.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.01,0.412169,16.841270,0.560516,0.561376
20250316.1929.no_constraint,[],NaN,0.415344,17.222221,0.573336,0.574074
20250317.0739.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.01,0.414815,17.412699,0.579289,0.580423
20250317.1912.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",0.10,0.386772,18.396826,0.614164,0.613227
20250317.1902.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",0.10,0.374074,18.777779,0.625840,0.625926
20250318.0328.constraints,"[Not Succession[a, a], Not Chain Succession[c, c], Not Succession[a, c], Not CoExistence[c, a]]",1.00,0.335979,19.095238,0.636447,0.636508
20250318.0433.constraints,"[Not Chain Succession[a, b], Not Chain Succession[a, a], Succession[c, c], Chain Response[c, b]]",1.00,0.305820,20.634920,0.687653,0.687831
20250318.0342.constraints,"[Alternate Precedence[c, b], Existence2[c], Alternate Succession[c, a], Not CoExistence[a, b], Not Chain Succession[c, b]]",1.00,0.095238,27.142857,0.904762,0.904762
20250318.0442.constraints,"[Response[a, c], Absence2[c], Alternate Response[b, b], Not CoExistence[b, b]]",1.00,0.000529,29.984127,0.999504,0.999471